config/routes.rb
FuzzyComputingMachine::Application.routes.draw do

  resources :answers

  resources :questions

  resources :interviews

  resources :publications

  resources :people

  resources :sources

  get '/subjects', to: 'subjects#index', as: 'subjects'

  get '/about', to: 'static#about', as: 'about'

  root 'home#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :interview
end

app/models/interview.rb
class Interview < ActiveRecord::Base

  has_one :raw_text

  belongs_to :publication

  has_many :questions
  has_many :answers

  has_and_belongs_to_many :people
  has_and_belongs_to_many :sources

  acts_as_taggable_on :subjects
end

app/models/person.rb
class Person < ActiveRecord::Base

  has_and_belongs_to_many :interviews
end

app/models/publication.rb
class Publication < ActiveRecord::Base

  has_many :interviews
end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :interview
end

app/models/raw_text.rb
class RawText < ActiveRecord::Base

  belongs_to :interview
  belongs_to :source
end

app/models/source.rb
class Source < ActiveRecord::Base

  has_many :raw_texts

  has_and_belongs_to_many :interviews
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  respond_to :html, :json

  def index
    respond_with @people = Person.all
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController

  respond_to :html, :json

  def index
    respond_with @sources = Source.all
  end

  def new
    respond_with @source = Source.new
  end

  private

  def source_params
    params.require(:source).permit(:name, :url, :description)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  respond_to :html

  def about
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/layouts/_footer.html.haml
%hr
  .footer
    %p &copy; HDN #{Time.now.year}

app/views/layouts/_jumbotron.html.haml
.jumbotron
  %h1 Marketing stuff!
  %p.lead Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
  %a.btn.btn-large.btn-success{:href => "#"} Get started today

app/views/layouts/_navigation.html.haml
.navbar
  .navbar-inner
    .container
      %ul.nav
        = active_link_to 'Home', root_path, active: :exclusive, wrap_tag: :li
        = active_link_to 'People', people_path, active: :inclusive, wrap_tag: :li
        = active_link_to 'Publications', publications_path, active: :inclusive, wrap_tag: :li
        = active_link_to 'Subjects', subjects_path, active: :inclusive, wrap_tag: :li
        = active_link_to 'About', about_path, active: :inclusive, wrap_tag: :li

app/views/layouts/_three_col.html.haml
.span4
  %h2 Heading
  %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
  %p
    %a.btn{:href => "#"} View details »
.span4
  %h2 Heading
  %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
  %p
    %a.btn{:href => "#"} View details »
.span4
  %h2 Heading
  %p Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.
  %p
    %a.btn{:href => "#"} View details »

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Good Questions
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container
      .masthead
        %h3.muted Good Questions
        = render 'layouts/navigation'
      = yield
      = render 'layouts/footer'